### PR TITLE
Integrate basic Dockerfile

### PR DESCRIPTION
**Pull request by rtizzy**
This will likely need to have a few changes take place. I will perform these later.

### CODE REVIEW

**Comment by rtizzy** [comment]
This needs to be configured to run as a non-root user. I will work on doing that later when I'm in my Linux install (Currently booted into Windows)

**Comment by macdja38** [comment]
if its to be included in the repo folder instead of the folder one above it (with the repo folder and config folder mounted in atrun time...) I should probably put all the src files in a src folder?

**Comment by macdja38** [comment]
@rtizzy Moved all the src files into a src folder. (also switched to typescript) so should be a lot easier to make a dockerfile for now. My one issue is uhh... shards... Do I put all the shards in one docker container, or do one container per shard. And if I do one container per shard how do I manage the containers.

**Comment by macdja38** [comment]
Created a new Dockerfile here https://github.com/macdja38/pvpcraft/commit/794f8167e4f7ca23485eb3778904ee08f0b0b77e which other than config I think does a bit better of a job now that we use typescript.

**Pull request closed without merging**
